gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Hello, traveler! I'm PROFESSOR\n"
	.string "OAK. Welcome to the EUROPEAN TOUR!\p"
	.string "I study how POKEMON share our\n"
	.string "towns, forests and old roads.$"

gOakSpeech_Text_ThisWorld::
    .string "From city parks to country paths…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…POKéMON live all around us!\n"
    .string "Each country has its own wildlife.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Some familiar POKEMON routes are\n"
	.string "changing. I need a partner who\p"
	.string "will listen, investigate and help.\n"
	.string "Meet our regional researchers.\p"
	.string "Your first POKEMON is waiting!$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is another young traveler.\p"
    .string "You share a love of POKéMON\n"
    .string "and a taste for adventure.\p"
    .string "What is your friend's name?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "What is your friend's name?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Choose your home country, then\n"
    .string "choose a regional first partner!\p"
    .string "Meet each city's guide and collect\n"
    .string "tour stamps. Europe awaits!$"
