"""Generate the GBA regional map from public-domain Natural Earth vector land.

Input is clipped vector geometry, not a hand-drawn approximation. Projection
uses one Mercator scale for both axes; no city is moved to make labels fit.
"""
import json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
LEFT,TOP,WIDTH,HEIGHT=86,18,148,87
def merc(lat):return math.log(math.tan(math.pi/4+math.radians(lat)/2))
SCALE=(HEIGHT-1)/(merc(60)-merc(46))
def project(lon,lat):
    return LEFT+(WIDTH-1)/2+SCALE*math.radians(lon-3), TOP+SCALE*(merc(60)-merc(lat))

def generate():
    rings=json.loads((ROOT/'data/geography/northwest-europe-land.json').read_text())['rings']
    pixels=set()
    for ring in rings:
        pts=[project(*p) for p in ring]
        for y in range(TOP,TOP+HEIGHT):
            scan=y+0.5;xs=[]
            for (x1,y1),(x2,y2) in zip(pts,pts[1:]+pts[:1]):
                if (y1<=scan<y2) or (y2<=scan<y1):xs.append(x1+(scan-y1)*(x2-x1)/(y2-y1))
            xs.sort()
            for a,b in zip(xs[::2],xs[1::2]):
                for x in range(max(LEFT,math.ceil(a-.5)),min(LEFT+WIDTH,math.ceil(b-.5))):pixels.add((x,y))
    spans=[]
    for y in range(TOP,TOP+HEIGHT):
        x=LEFT
        while x<LEFT+WIDTH:
            if (x,y) not in pixels:x+=1;continue
            start=x
            while (x,y) in pixels:x+=1
            spans.append((start,y,x-start))
    cities=json.loads((ROOT/'data/geography/cities.json').read_text())['cities']
    points=[tuple(round(v) for v in project(c['longitude'],c['latitude'])) for c in cities]
    out=['// Generated by scripts/build-geographic-map.py. Made with Natural Earth.',
         'static const u8 sLandSpans[][3] = {']
    out += ['    {%d, %d, %d},'%p for p in spans]
    out+=['};','static const u8 sCityX[] = {'+', '.join(str(p[0]) for p in points)+'};',
          'static const u8 sCityY[] = {'+', '.join(str(p[1]) for p in points)+'};','']
    (ROOT/'src/data/europe_geography.h').write_text('\n'.join(out),newline='\n')
    print(f'Generated {len(spans)} coastline spans and {len(points)} geographically positioned stops.')
if __name__=='__main__':generate()
